#!groovy

/**
 *  Jenkinsfile: catalogador-tfg - Pipeline produccion
 *  @hugo-lorenzo-mato
 */

def appName = 'catalogador-tfg'
def nodeImage = 'node:6'
def gradleImage = 'gradle:4.0.2'
def mavenChromeImage = 'markhobson/maven-chrome:latest'
def flywayImage = 'boxfuse/flyway:5'

def db = null
def dbHostname = null
def dbName = 'postgres'
def dbUser = 'postgres'
def dbPassword = 'postgres'

def web = null
def webHostname = null

node() {
    try {
        stage('Git: Checkout') {
            echo 'Checking out git repository'
            sh "git config --global credential.helper 'cache --timeout=3600'"
        checkout scm
        }
        
        
        
        docker.image(nodeImage).inside("-u 0:0") {
            stage('Node: Instalando dependencias') {
                sh "cd appserver/application && npm install"
            }
            stage('Node: Empaquetado web') {
                sh "cd appserver/application && npm run build"
            }
        }

        docker.image(gradleImage).inside("-u 0:0") {
            stage('Gradle: Compilando') {
                sh "cd appserver/application && gradle clean && gradle war"
            }
        }

    } finally {
        sh "whoami"
    }

}


node() {
    stage('Test: Install') {
        sh "echo 'TESTEANDO'"
    }
}  

node() {
    stage('Test: usuario') {
        sh "echo $whoami"
    }
}
