# ===================================================================
# Spring Boot configuration for the "prod" profile.
#
# This configuracion overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:

    # Configuración de la BASE DE DATOS
#    datasource:
#        dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
#        url: jdbc:postgresql://ggal1701.c0gqvbyobsaf.us-east-2.rds.amazonaws.com:5432/ggal1701
#        username: postgres
#        password: postgres
#        maximum-pool-size: 5

    application:
        url: http://localhost:8080
    profiles:
        active: prod
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: false

server:
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json

