version: "3"
services:
  postgres:
    image: uggo/catalogador-postgres:initial
    ports:
      - "5432:5432"
    volumes:
      - "/tmp:/tmp"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
  web:
    # replace username/repo:tag with your name and image details
    image: uggo/catalogador-tomcat:part2
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "80:80"
    networks:
      - webnet
    environment:
      #- "JAVA_OPTS: '-Dspring.datasource.url=jdbc:postgresql://ggal1701.c0gqvbyobsaf.us-east-2.rds.amazonaws.com:5432/ggal1701 -Dspring.datasource.username=postgres -Dspring.datasource.password=postgres'"
      - JDBC_URL=jdbc:postgresql://ggal1701.c0gqvbyobsaf.us-east-2.rds.amazonaws.com:5432:5432/ggal1701
      - DATABASE_USERNAME= postgres
      - DATABASE_PASSWORD=postgres
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
networks:
  webnet:
